github.com:
    users:
        arch-based:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: arch-based
