github.com:
    users:
        arch-based:
            oauth_token: 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
    git_protocol: ssh
    user: arch-based
    oauth_token: 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
