theme = "catppuccin_mocha"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "separator", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-s = ":w"
S-w = ":wq"
S-q = ":q"
A-w = ":wq!"
A-q = ":q!"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
